baseURL = 'https://scriptling.dev/'
languageCode = 'en-US'
title = 'Scriptling'

[outputs]
  home = ['HTML', 'JSON']

[params]
  githubURL = "https://github.com/paularlott/scriptling"
  copyright = "Paul Arlott"
  defaultTheme = "dark"  # Options: "light" or "dark"
  includeSections = ["docs"]

  [params.navigation]
    [[params.navigation.header]]
      name = 'Home'
      url = '/'
    [[params.navigation.header]]
      name = 'Docs'
      url = '/docs'
    [[params.navigation.header]]
      name = 'Changelog'
      url = '/docs/changelog/'

[build]
  [build.buildStats]
    enable = true
  [[build.cachebusters]]
    source = 'assets/notwatching/hugo_stats\.json'
    target = 'css'
  [[build.cachebusters]]
    source = '(postcss|tailwind)\.config\.js'
    target = 'css'

[module]
  [module.hugoVersion]
    extended = true
    min = '0.150.0'

  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

  [markup.highlight]
    #style = 'catppuccin-frappe'
    noClasses = false
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = false
    tabWidth = 2

  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    source = "assets/scss"
    target = "assets/scss"
  [[module.mounts]]
    disableWatch = true
    source = 'hugo_stats.json'
    target = 'assets/notwatching/hugo_stats.json'